load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")
load("@com_google_protobuf//:protobuf.bzl", "cc_proto_library")

py_proto_library(
    name = "remoteadd_py_proto",
    srcs = ["remoteadd.proto"],
    visibility = ["//visibility:public"]
)

cc_proto_library(
    name = "remoteadd_cc_proto",
    srcs = ["remoteadd.proto"],
    visibility = ["//visibility:public"]
)
